### ISSUE TITLE
Custom CSS not loading?

### ISSUE THREAD

**Issue by Derpford** [J-Siu/hugo-theme-sk3#29]
I have the following in a file called `sidebar.css` under `static` in the root dir of my site:
```css
aside {
	width: 32%;
	background-color: "#FFB000";
	float: right;
}
/* for testing purposes, to verify that the file is loading */
body {
	background-color: "green";
}
```
I then added this to my config.toml:
```toml
[Params]
#...
custom_css = ["/sidebar.css"]
```
Obviously this *should* turn the whole page green (and also turn asides into sidebars). However, it doesn't appear to be loading, even though Hugo picks up on the existence of this file and reloads the page when I change it.

**Comment by Derpford** [comment]
So apparently Hugo is skipping my raw HTML inside my markdown file, which means my `<aside>` tag is also not being picked up on.

**Comment by Derpford** [comment]
Issue resolved by setting the following in the config file:
```toml
# enable raw html in markdown
[markup.goldmark.renderer]
unsafe= true
```
